### ISSUE TITLE
hipchat_notifier_v2.py is not pushing notifications

### ISSUE THREAD

**Issue by vastbinderj** [shippableSamples/sample-hipchat-notifications#3]
I am not seeing notifications in hipchat, nor am i seeing errors on shippable with the script.

**Comment by vladdancer** [comment]
Hi all.
I got errors that relates to the hipchat auth and I've did some research.
Here an error:

```
{
  "error": {
    "code": 401,
    "message": "Invalid OAuth session",
    "type": "Unauthorized"
  }
}
```

Shippable YML:

``` yml
env:
  global:
    - secure: hc_token_encrypted
    - HC_ROOM=111111
    - PROJECT="Group with whitespace"

before_install:
 - wget https://raw.githubusercontent.com/shippableSamples/sample-hipchat-notifications/master/hipchat_notifier_v2.py -O $SHIPPABLE_REPO_DIR/hc-notify.py

.....

after_success:
  - cd $SHIPPABLE_REPO_DIR
  - python hc-notify.py --project $PROJECT --room $HC_ROOM --token $HC_TOKEN -s

```

This error causes when python tries to send request to the hipchat with empty params (such as room id, token). So I dig deeper and get that `getopt.getopt(sys.argv` can't parse script cli arguments. But shell command `echo` (eg `echo $HC_TOKEN`) shows them ok.

Than I've tried to delete a white space inside env var `PROJECT`, and... ta-da - no errors in this time.

Very strange, but on local machine I can't reproduce this error.
